### ISSUE TITLE
Favorite Page

### ISSUE THREAD

**Issue by MaxReinmueller** [MaxReinmueller/Stock-View#2]
### Job story
As an investor I want to track my favorite stocks so that I can stay up to date

### Acceptance Criteria
- [x] favorite.html stocks the user has marked as favorites are stored in a table
- [x] favorite.html when the user clicks one of the stocks in the table, a pricing graph is displayed below

### Tasks
- [x] task 1

**Comment by kaur1081** [comment]
Do you want pricing displayed below or by the side with graphical picture

**Comment by kaur1081** [comment]
I don't know if iI have to close the issue?
